server:
  port: 9501
spring:
  application:
    name: microcloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka,http://edmin:edmin@eureka-7002.com:7002/eureka,http://edmin:edmin@eureka-7003.com:7003/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: gateway-9501.com
    prefer-ip-address: true

    ## 以下两项配置不建议自定义配置
    # 如果从上一次心跳到现在超过了5秒的间隔，还没有心跳的话，就认为当前服务已宕掉（默认是90秒）
#    lease-expiration-duration-in-seconds: 5
    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2

info:
  app.name: microcloud-zuul-gateway
  # "$$"写法依赖maven-resources-plugin插件和<resources>配置
  build.artifactId: $project.artifactId$
  build.version: $project.version$


# zuul路由方式一：
#zuul:
#  prefix: /zuul-proxy
#  routes:
#    microcloud-provider-company: /company-proxy/**

# zuul路由方式二：
zuul:
#  ignored-services的意义是忽略通过服务名可以访问微服务(添加完成之后不能通过服务名访问微服务)
#  ignored-services: microcloud-provider-company # 方法一：忽略服务名称访问
#  ignored-services: "*" # 方法二：如果微服务比较多，则采用通配符的方式配置，进行忽略
  routes:
    company-proxy:
      path: /company-proxy/**
      serviceId: microcloud-provider-company
    dept-proxy:
      path: /dept-proxy/**
      serviceId: microcloud-provider-dept
security:
  basic:
    enabled: true
  user:
    name: zdmin
    password: zdmin
