server:
  port: 9501
spring:
  application:
    name: microcloud-zuul-gateway
  zipkin:
    base-url: http://zipkin.com:9601 # 所有的数据提交到此服务之中
  sleuth:
    sampler:
      percentage: 1.0 #抽样百分比，默认0.1
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka,http://edmin:edmin@eureka-7002.com:7002/eureka,http://edmin:edmin@eureka-7003.com:7003/eureka
  instance:
    # 在信息列表时显示主机名称
    instance-id: gateway-9501.com
    prefer-ip-address: true

    ## 以下两项配置不建议自定义配置
    # 如果从上一次心跳到现在超过了5秒的间隔，还没有心跳的话，就认为当前服务已宕掉（默认是90秒）
#    lease-expiration-duration-in-seconds: 5
    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2

info:
  app.name: microcloud-zuul-gateway
  # "$$"写法依赖maven-resources-plugin插件和<resources>配置
  build.artifactId: $project.artifactId$
  build.version: $project.version$


# zuul路由方式一：
#zuul:
#  prefix: /zuul-proxy
#  routes:
#    microcloud-provider-company: /company-proxy/**

# zuul路由方式二：
zuul:
#  ignored-services的意义是忽略通过服务名可以访问微服务(添加完成之后不能通过服务名访问微服务)
#  ignored-services: microcloud-provider-company # 方法一：忽略服务名称访问
#  ignored-services: "*" # 方法二：如果微服务比较多，则采用通配符的方式配置，进行忽略
  routes:
    company-proxy:
      path: /company-proxy/**
      serviceId: microcloud-provider-company
    dept-proxy:
      path: /dept-proxy/**
      serviceId: microcloud-provider-dept
    upload-proxy:
      path: /upload-proxy/**
      serviceId: microcloud-provider-upload
# 通过zuul对上传微服务进行代理时，如果上传的文件大小较小时，是可以正常上传的，但是如果上传的文件较大时，此时通过zuul进行代理上传时会报错。
# 解决办法：在请求路径前加上“zuul/**”前缀，此时zuul对上传操作不再进行代理，而是直接交由目标微服务进行操作。
#  eg:
#                curl -F "file=@F:/pictures/b.mp4" http://zdmin:zdmin@gateway-9501.com:9501/upload-proxy/upload
# 交由目标微服务： curl -F "file=@F:/pictures/b.mp4" http://zdmin:zdmin@gateway-9501.com:9501/zuul/upload-proxy/upload

# 在上传大文件的过程中，可能会出现timeout超时的情况，
# 解决办法：在zuul的application.yml配置文件中加入如下配置：
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

security:
  basic:
    enabled: true
  user:
    name: zdmin
    password: zdmin
