server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka,http://edmin:edmin@eureka-7002.com:7002/eureka,http://edmin:edmin@eureka-7003.com:7003/eureka
    register-with-eureka: false
feign:
  compression:
    request:
      mime-types: # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      # 超过2048的字节会进行压缩
      min-request-size: 2048

# 设置日志打印级别
logging:
  level:
    cn.mldn.service: DEBUG
