server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7001.com:7001/eureka,http://edmin:edmin@eureka-7002.com:7002/eureka,http://edmin:edmin@eureka-7003.com:7003/eureka
    register-with-eureka: false
  instance:
    instance-id: upload.com # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为IP地址

# 设置日志打印级别
logging:
  level: DEBUG
spring:
  thymeleaf:
    enabled: true
    prefix: classpath: view/templates/
    suffix: .html
    encoding: UTF-8
    cache: true
  resources:
    chain:
      enabled: true